### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Tskuno** [BrianOstrander/pz-save-our-station#1]
Getting Error fatal_(number shifts between 1-4) then diagnostic code comes up, but doesn't give any code whatsoever, just the phrase Diagnostic_code

**Comment by Tskuno** [comment]
This is on a MP server btw. Does have survivor radio, but no other radio mods at all.

**Comment by BrianOstrander** [comment]
Resolved in recent updates, thanks for the bug report.
